name: attendance_qr
description: Control de Asistencia con código QR
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.3.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  